### ISSUE TITLE
How to put all posts in site root instead of putting in folder such as "blog"?

### ISSUE THREAD

**Issue by yanglr** [PiranhaCMS/piranha.core.templates#38]
Hi,
considering SEO, for new site, I need to put all contents in site root (eg. `do.geekzl.com`). 
Then I also need pagination in the home page.

Does `piranha.core.templates` support these requirements?

If yes, how to setting in the manager page to achieve it?
Thanks~

**Comment by tidyui** [comment]
@yanglr The default archive routing doesn't not support having blog post url's like

~~~
do.geekzl.com/my-post
~~~

The routing is build around the posts being prefixed with the name of the archive page they belong to, for example:

~~~
do.geekzl.com/my-blog/my-post
~~~

Now since `ASP.NET` is very modular you could just add your own custom middleware before the Piranha middleware and rewrite request for posts in the site root to the expected url of the framework.

Regards

**Comment by yanglr** [comment]
Cool, thanks~
